export const bonusTypes = [
    {
        id: 0,
        name: 'Freespin'
    },
    {
        id: 1,
        name: 'Casino'
    },
    {
        id: 2,
        name: 'Sport'
    },
]

export const bonusRequestStatusEnum = [
    {
        id: 0,
        name: 'Pending'
    },
    {
        id: 1,
        name: 'Processing'
    },
    {
        id: 2,
        name: 'Accepted'
    },
    {
        id: 3,
        name: 'Rejected'
    },
]

export const providers = [
  { id: 29, name: "1x2 Network" },
  { id: 374, name: "3 Oaks Gaming" },
  { id: 407, name: "7Mojos" },
  { id: 415, name: "7Mojos Live Casino" },
  { id: 369, name: "Ad Lunam" },
  { id: 325, name: "AGT Software" },
  { id: 324, name: "Amigo Gaming" },
  { id: 414, name: "Amusnet Interactive" },
  { id: 197, name: "Apollo Games" },
  { id: 404, name: "AvatarUX" },
  { id: 401, name: "Aviatrix" },
  { id: 348, name: "Barbara Bang" },
  { id: 144, name: "BetGames.TV" },
  { id: 405, name: "Betsoft Gaming" },
  { id: 134, name: "BetSolutions" },
  { id: 468, name: "BGaming" },
  { id: 690, name: "Big Time Gaming" },
  { id: 74, name: "Blueprint Gaming" },
  { id: 353, name: "Boldplay" },
  { id: 505, name: "Booming" },
  { id: 160, name: "Cool Games" },
  { id: 205, name: "CQ9 Gaming" },
  { id: 301, name: "CT Interactive" },
  { id: 88, name: "Dragoon Soft" },
  { id: 326, name: "Elbet" },
  { id: 19, name: "Endorphina" },
  { id: 252, name: "Eurasian Gaming" },
  { id: 122, name: "Evolution" },
  { id: 127, name: "Evolution Premium" },
  { id: 103, name: "Evoplay" },
  { id: 627, name: "Ezugi" },
  { id: 629, name: "Ezugi Premium" },
  { id: 333, name: "Fa Chai Game" },
  { id: 85, name: "Fantasma Games" },
  { id: 138, name: "Fazi Interactive" },
  { id: 145, name: "Felix Gaming" },
  { id: 154, name: "Fugaso" },
  { id: 158, name: "Funky Games" },
  { id: 149, name: "FunTa Gaming" },
  { id: 26, name: "GameArt" },
  { id: 143, name: "Games Inc" },
  { id: 400, name: "Gamzix" },
  { id: 7, name: "GoldenRace" },
  { id: 21, name: "Habanero" },
  { id: 59, name: "Iron Dog Studio" },
  { id: 288, name: "JILI Games" },
  { id: 106, name: "KA Gaming" },
  { id: 75, name: "Kalamba Games" },
  { id: 84, name: "Kiron Interactive" },
  { id: 67, name: "Leap Gaming" },
  { id: 399, name: "LuckyStreak" },
  { id: 387, name: "Mancala Gaming" },
  { id: 102, name: "Mascot Gaming" },
  { id: 604, name: "Microgaming" },
  { id: 41, name: "Mobilots" },
  { id: 132, name: "MrSlotty" },
  { id: 92, name: "NetEnt" },
  { id: 141, name: "NetGame Entertainment" },
  { id: 680, name: "NoLimit" },
  { id: 473, name: "Novomatic" },
  { id: 474, name: "Novomatic Premium" },
  { id: 86, name: "OMI Gaming" },
  { id: 43, name: "OneTouch" },
  { id: 313, name: "Onlyplay" },
  { id: 469, name: "Peter & Sons" },
  { id: 358, name: "PG Soft" },
  { id: 116, name: "Platipus Gaming" },
  { id: 413, name: "Play'n GO" },
  { id: 455, name: "Playson" },
  { id: 395, name: "Playtech Casino" },
  { id: 396, name: "Playtech Live" },
  { id: 22, name: "Pragmatic Play" },
  { id: 129, name: "Pragmatic Play Live" },
  { id: 125, name: "Print Studios" },
  { id: 368, name: "Prospect Gaming" },
  { id: 98, name: "Quickspin" },
  { id: 76, name: "RealTime Gaming" },
  { id: 66, name: "Red Rake Gaming" },
  { id: 89, name: "Red Tiger Gaming" },
  { id: 120, name: "Revolver Gaming" },
  { id: 371, name: "Rival Gaming" },
  { id: 328, name: "RubyPlay" },
  { id: 567, name: "Skywind Group" },
  { id: 568, name: "Skywind Live Casino" },
  { id: 51, name: "Slotmill" },
  { id: 58, name: "SmartSoft Gaming" },
  { id: 77, name: "Spearhead Studios" },
  { id: 8, name: "Spinmatic Entertainment" },
  { id: 162, name: "Spinomenal" },
  { id: 458, name: "Spribe" },
  { id: 54, name: "Thunderkick" },
  { id: 23, name: "Tom Horn Gaming" },
  { id: 139, name: "TPG Triple Profits Games" },
  { id: 30, name: "Triple Cherry" },
  { id: 321, name: "Turbo Games" },
  { id: 2, name: "TVBET" },
  { id: 384, name: "Urgent Games" },
  { id: 375, name: "Vivo Gaming" },
  { id: 121, name: "Wazdan" },
  { id: 487, name: "Winfinity Live" },
  { id: 163, name: "XPG XproGaming" },
  { id: 403, name: "Yggdrasil Gaming" },
  { id: 349, name: "ZeusPlay" }
];

